### ISSUE TITLE
hex.pm version on GitHub

### ISSUE THREAD

**Issue by El-76** [appodeal/clickhousex#25]
The project README states one of the installation methods is via hex.pm.
The official hex.pm project page (https://hex.pm/packages/clickhousex) refers to this repository.
However, I failed to find source version in the repo that corresponds to the hex archive.
This prevents me from forking the project and making modifications properly.

Please advise.

**Comment by sirikid** [comment]
Unfortunately we do not know when the versions were built that are currently available at hex.pm. The next version will definitely be tagged before uploading.

**Comment by jrogov** [comment]
Starting from 0.5.0 all versions will be tagged, which is already done.
