### ISSUE TITLE
Bulk data insert fails

### ISSUE THREAD

**Issue by segaz2002** [appodeal/clickhousex#3]
When I tried inserting multiple rows via `Clickhousex.query/1`
 I get 

```code
%Clickhousex.Error{code: :unknown, constraint_violations: [], message: ""}}
```

I play around with the limit of data I am uploading at a time, it seem 20 is the max number of rows allowed.

**Comment by jpascal** [comment]
Hello, @segaz2002. Do you have some messages in log about this? Do you try reduce size of single inserted row? Could you provide example of code?

**Comment by jpascal** [comment]
@segaz2002 please, look at https://github.com/appodeal/clickhousex/pull/2.
