### ISSUE TITLE
Why lists are converted to binaries?

### ISSUE THREAD

**Issue by LeandroLM** [appodeal/clickhousex#4]
Out of the box, Ecto [supports arrays](https://hexdocs.pm/ecto/Ecto.Schema.html#module-primitive-types) as a primitive type. However, Clickhousex [converts](https://github.com/appodeal/clickhousex/blob/master/lib/clickhousex/query.ex#L44) lists to binary when decoding the results, and that gives me an error when trying to use a field with type `{:array, :integer}` in an Ecto schema.

```elixir
  def decode(_query, result, _opts) do
    case result.command do
      :selected ->
        rows = result.rows
        new_rows = Enum.map(rows, fn el ->
          list1 = Tuple.to_list(el)
          Enum.map(list1, fn el1 -> # why is this necessary?
            cond do
              is_list(el1) ->
                to_string(el1)
              true ->
                el1
            end
          end)
        end)
        Map.put(result, :rows, new_rows)
      _ ->
        result
    end
  end
```

I ran the project locally without this conversion and it worked as expected, giving me a list as a result. Can this be removed?

cc @albertosca

**Comment by hissssst** [comment]
Merged, closing
@LeandroLM, reopen if needed
