### ISSUE TITLE
kind takeover proposal

### ISSUE THREAD

**Issue by ruslandoga** [appodeal/clickhousex#46]
👋

If this repo and org are no longer useful or used by the original authors, @plausible is interested in taking it over and carrying for it as one of its own :)

Sorry if I got the picture wrong and the repo is still being used and maintained.

**Comment by hissssst** [comment]
I am maintaining this repo, but in __very slow__ mode. You can always submit PRs and we'll mention you in README contributors sections. Thanks for submitted issues.
